# TODO MAKE POPUP SPECIFIERS PROTOTYPES THIS IS UNBEARABLE
- type: Interaction
  id: Base
  abstract: true
  successPopup:
    prefix: success
    popupType: Medium
    logPopup: true
    logChannel: Emotes

# Base global interaction
- type: Interaction
  id: BaseGlobal
  parent: Base
  abstract: true
  global: true

# Base interaction that involves hands
- type: Interaction
  id: BaseHands
  parent: Base
  requiresHands: true
  requiresCanInteract: true
  contactInteraction: true
  range:
    max: 2
  successPopup:
    prefix: success
    popupType: Medium
    logPopup: true
    logChannel: Emotesdw
    sound: {path: /Audio/Effects/thudswoosh.ogg}

# TODO ALL OF THE BELOW SHOULD BE GONE IN FAVOR OF PROTOTYPES
# I HATE THESE
# Base interaction that shows a popup when failed. The popup is not shown to others by default.
- type: Interaction
  id: BaseFailable
  parent: Base
  abstract: true
  failurePopup:
    prefix: fail
    others: null
    popupType: SmallCaution

# Base delayed interaction that shows a popup when started. The popup is not shown to others by default.
- type: Interaction
  id: BaseDelayedPopup
  parent: Base
  abstract: true
  delayedPopup:
    prefix: delayed
    others: null
    logPopup: false
    popupType: Small
